services:
  ui:
    entrypoint: "npm run dev -- --host --port 3000"
    develop:
      watch:
        - action: "sync"
          path: "./ui"
          target: "/app"
          ignore:
            - "node_modules/"
        - action: "sync+restart"
          path: "./ui/vite.config.ts"
          target: "/app/vite.config.ts"
        - action: "rebuild"
          path: "./ui/package-lock.json"
