services:
  api:
    entrypoint: "npm run dev"
    develop:
      watch:
        - action: "sync"
          path: "./api"
          target: "/app"
          ignore:
            - "node_modules/"
  runtime:
    develop:
      watch:
        - action: "sync+restart"
          path: "./runtime"
          target: "/app"
  ui:
    entrypoint: "npm run dev -- --host --port 3000"
    develop:
      watch:
        - action: "sync"
          path: "./ui"
          target: "/app"
          ignore:
            - "node_modules/"
