version: "3.8"
services:
  storage:
    build:
      context: "storage"
    restart: "always"
    volumes:
      - "./storage-data:/deployments" # TODO: make a proper volume not only a bind mount
    ports: # TODO: do not expose the storage to the public, instead only access this container indirectly through the deploy-server
      - "8080:80"
  mqtt:
    build:
      context: "mqtt"
    restart: "always"
    ports: # TODO: do not expose the mqtt to the public, instead only access this container indirectly through the deploy-server
      - "1883:1883"
  runtime:
    build:
      context: "runtime"
    restart: "always"
    deploy:
      mode: "replicated"
      replicas: 2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.runtime.rule=HostRegexp(`.+\\.apps\\.localhost`)"
    depends_on:
      - "storage"
      - "loki"
      - "mqtt"
  loki:
    image: "grafana/loki:3.3.0"
    restart: "always"
    volumes:
      - "loki:/loki"
  ui:
    build:
      context: "ui"
    restart: "always"
    depends_on:
      - "loki"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui.rule=Host(`app.localhost`)"
  ingress:
    image: "traefik:v3.0"
    restart: "always"
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--api.insecure"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  # storage:
  loki:
