on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: api

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm ci --prefer-offline --no-audit
      - run: npm run check:types
      - run: npm run check:format
      - run: npm run check:lint
